site_name: Blog Example
site_url: https://liang2kl.github.io/mkdocs-blogging-plugin-example/
repo_url: https://github.com/liang2kl/mkdocs-blogging-plugin-example/
repo_name: liang2kl/mkdocs-blogging-plugin-example
edit_uri: ""

theme:
  name: 'material'

plugins:
  - blogging:
      dirs:
        - articles
      template: override/custom-blog.html
      locale: en
      time_format: '%d/%m/%y %H:%M:%S'
      meta_time_format: '%Y-%m-%d %H:%M:%S'
      features:
        tags:
          index_page: tags.md
          insert: top

copyright: Copyright &copy; 2021 Liang Yesheng